version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: gestao_escolar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emmanuel1
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - edu-network

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gestao_escolar
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: emmanuel1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - edu-network

volumes:
  db_data:

networks:
  edu-network:
    external: true